// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB84f8ZNJB84HpvlCt5cUSvaQLx5_r222g',
    appId: '1:263260060360:web:561d0531670c1227f683fd',
    messagingSenderId: '263260060360',
    projectId: 'lockerscan-3d7cb',
    authDomain: 'lockerscan-3d7cb.firebaseapp.com',
    databaseURL: 'https://lockerscan-3d7cb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lockerscan-3d7cb.firebasestorage.app',
    measurementId: 'G-B1JNEL311D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqYjgPS6uoKsxAYsIrrXzu8pYMpk9o6cc',
    appId: '1:263260060360:android:f9f0e83923b93634f683fd',
    messagingSenderId: '263260060360',
    projectId: 'lockerscan-3d7cb',
    databaseURL: 'https://lockerscan-3d7cb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lockerscan-3d7cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBozwKJHPZFQCYBt59UWjt2mmSnQ1CZmyc',
    appId: '1:263260060360:ios:88a8245a8220004ef683fd',
    messagingSenderId: '263260060360',
    projectId: 'lockerscan-3d7cb',
    databaseURL: 'https://lockerscan-3d7cb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lockerscan-3d7cb.firebasestorage.app',
    iosBundleId: 'com.example.lockerScan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBozwKJHPZFQCYBt59UWjt2mmSnQ1CZmyc',
    appId: '1:263260060360:ios:88a8245a8220004ef683fd',
    messagingSenderId: '263260060360',
    projectId: 'lockerscan-3d7cb',
    databaseURL: 'https://lockerscan-3d7cb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lockerscan-3d7cb.firebasestorage.app',
    iosBundleId: 'com.example.lockerScan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB84f8ZNJB84HpvlCt5cUSvaQLx5_r222g',
    appId: '1:263260060360:web:6a68e0e9ea035a42f683fd',
    messagingSenderId: '263260060360',
    projectId: 'lockerscan-3d7cb',
    authDomain: 'lockerscan-3d7cb.firebaseapp.com',
    databaseURL: 'https://lockerscan-3d7cb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lockerscan-3d7cb.firebasestorage.app',
    measurementId: 'G-MF8RZM2K2K',
  );
}
